import { JournalEntry, ChartOfAccountWithChildren } from "@/types";

// ── Dummy Journal Entries ──────────────────────────────────────────────────
export const dummyJournals: JournalEntry[] = [
	{
		id: "j1",
		date: "2026-04-21T10:30:00Z",
		description: "Pembelian Perlengkapan Kantor",
		createdAt: "2026-04-21T10:30:00Z",
		updatedAt: "2026-04-21T10:30:00Z",
		lines: [
			{
				id: "l1",
				journalEntryId: "j1",
				accountId: "a6",
				debit: "500000",
				credit: "0",
				account: {
					id: "a6",
					code: "5.01.01.04",
					name: "Biaya Perlengkapan",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p5",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l2",
				journalEntryId: "j1",
				accountId: "a1",
				debit: "0",
				credit: "500000",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j2",
		date: "2026-04-21T09:15:00Z",
		description: "Penerimaan Pendapatan Jasa",
		createdAt: "2026-04-21T09:15:00Z",
		updatedAt: "2026-04-21T09:15:00Z",
		lines: [
			{
				id: "l3",
				journalEntryId: "j2",
				accountId: "a1",
				debit: "2000000",
				credit: "0",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l4",
				journalEntryId: "j2",
				accountId: "a7",
				debit: "0",
				credit: "2000000",
				account: {
					id: "a7",
					code: "4.01.01.01",
					name: "Pendapatan Jasa",
					type: "REVENUE",
					isPosting: true,
					parentId: "p6",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j3",
		date: "2026-04-20T14:22:00Z",
		description: "Pembayaran Hutang Supplier",
		createdAt: "2026-04-20T14:22:00Z",
		updatedAt: "2026-04-20T14:22:00Z",
		lines: [
			{
				id: "l5",
				journalEntryId: "j3",
				accountId: "a8",
				debit: "1200000",
				credit: "0",
				account: {
					id: "a8",
					code: "2.01.01.00",
					name: "Hutang Dagang",
					type: "LIABILITY",
					isPosting: true,
					parentId: "p7",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l6",
				journalEntryId: "j3",
				accountId: "a2",
				debit: "0",
				credit: "1200000",
				account: {
					id: "a2",
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: "p2",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j4",
		date: "2026-04-20T11:00:00Z",
		description: "Gaji + Bonus Karyawan",
		createdAt: "2026-04-20T11:00:00Z",
		updatedAt: "2026-04-20T11:00:00Z",
		lines: [
			{
				id: "l7",
				journalEntryId: "j4",
				accountId: "a9",
				debit: "4000000",
				credit: "0",
				account: {
					id: "a9",
					code: "5.04.01.01",
					name: "Beban Gaji",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p8",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l8",
				journalEntryId: "j4",
				accountId: "a10",
				debit: "1000000",
				credit: "0",
				account: {
					id: "a10",
					code: "5.04.01.02",
					name: "Beban Bonus",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p8",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l9",
				journalEntryId: "j4",
				accountId: "a1",
				debit: "0",
				credit: "5000000",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j5",
		date: "2026-04-19T08:00:00Z",
		description: "Setoran Modal Awal",
		createdAt: "2026-04-19T08:00:00Z",
		updatedAt: "2026-04-19T08:00:00Z",
		lines: [
			{
				id: "l10",
				journalEntryId: "j5",
				accountId: "a2",
				debit: "50000000",
				credit: "0",
				account: {
					id: "a2",
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: "p2",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l11",
				journalEntryId: "j5",
				accountId: "a11",
				debit: "0",
				credit: "50000000",
				account: {
					id: "a11",
					code: "3.00.00.00",
					name: "Modal",
					type: "EQUITY",
					isPosting: false,
					parentId: null,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	// Add more dummy entries here if needed
	{
		id: "j6",
		date: "2026-04-21T10:30:00Z",
		description: "Pembelian Perlengkapan Kantor",
		createdAt: "2026-04-21T10:30:00Z",
		updatedAt: "2026-04-21T10:30:00Z",
		lines: [
			{
				id: "l1",
				journalEntryId: "j1",
				accountId: "a6",
				debit: "500000",
				credit: "0",
				account: {
					id: "a6",
					code: "5.01.01.04",
					name: "Biaya Perlengkapan",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p5",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l2",
				journalEntryId: "j1",
				accountId: "a1",
				debit: "0",
				credit: "500000",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j7",
		date: "2026-04-21T09:15:00Z",
		description: "Penerimaan Pendapatan Jasa",
		createdAt: "2026-04-21T09:15:00Z",
		updatedAt: "2026-04-21T09:15:00Z",
		lines: [
			{
				id: "l3",
				journalEntryId: "j2",
				accountId: "a1",
				debit: "2000000",
				credit: "0",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l4",
				journalEntryId: "j2",
				accountId: "a7",
				debit: "0",
				credit: "2000000",
				account: {
					id: "a7",
					code: "4.01.01.01",
					name: "Pendapatan Jasa",
					type: "REVENUE",
					isPosting: true,
					parentId: "p6",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j8",
		date: "2026-04-20T14:22:00Z",
		description: "Pembayaran Hutang Supplier",
		createdAt: "2026-04-20T14:22:00Z",
		updatedAt: "2026-04-20T14:22:00Z",
		lines: [
			{
				id: "l5",
				journalEntryId: "j3",
				accountId: "a8",
				debit: "1200000",
				credit: "0",
				account: {
					id: "a8",
					code: "2.01.01.00",
					name: "Hutang Dagang",
					type: "LIABILITY",
					isPosting: true,
					parentId: "p7",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l6",
				journalEntryId: "j3",
				accountId: "a2",
				debit: "0",
				credit: "1200000",
				account: {
					id: "a2",
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: "p2",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j9",
		date: "2026-04-20T11:00:00Z",
		description: "Gaji + Bonus Karyawan",
		createdAt: "2026-04-20T11:00:00Z",
		updatedAt: "2026-04-20T11:00:00Z",
		lines: [
			{
				id: "l7",
				journalEntryId: "j4",
				accountId: "a9",
				debit: "4000000",
				credit: "0",
				account: {
					id: "a9",
					code: "5.04.01.01",
					name: "Beban Gaji",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p8",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l8",
				journalEntryId: "j4",
				accountId: "a10",
				debit: "1000000",
				credit: "0",
				account: {
					id: "a10",
					code: "5.04.01.02",
					name: "Beban Bonus",
					type: "EXPENSE",
					isPosting: true,
					parentId: "p8",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l9",
				journalEntryId: "j4",
				accountId: "a1",
				debit: "0",
				credit: "5000000",
				account: {
					id: "a1",
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: "p1",
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: "j10",
		date: "2026-04-19T08:00:00Z",
		description: "Setoran Modal Awal",
		createdAt: "2026-04-19T08:00:00Z",
		updatedAt: "2026-04-19T08:00:00Z",
		lines: [
			{
				id: "l10",
				journalEntryId: "j5",
				accountId: "a2",
				debit: "50000000",
				credit: "0",
				account: {
					id: "a2",
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: "p2",
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: "l11",
				journalEntryId: "j5",
				accountId: "a11",
				debit: "0",
				credit: "50000000",
				account: {
					id: "a11",
					code: "3.00.00.00",
					name: "Modal",
					type: "EQUITY",
					isPosting: false,
					parentId: null,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
];

// ── Dummy COA Tree (Asset only, berkepala 1) ───────────────────────────────
export const dummyAssetTree: ChartOfAccountWithChildren[] = [
	{
		id: "p1",
		code: "1.01.00.00",
		name: "Aset Lancar",
		type: "ASSET",
		isPosting: false,
		parentId: null,
		createdAt: "",
		updatedAt: "",
		children: [
			{
				id: "p2",
				code: "1.01.01.00",
				name: "Bank",
				type: "ASSET",
				isPosting: false,
				parentId: "p1",
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: "a1",
						code: "1.01.01.01",
						name: "Mandiri - Main",
						type: "ASSET",
						isPosting: true,
						parentId: "p2",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: "a2",
						code: "1.01.01.02",
						name: "BCA - Main",
						type: "ASSET",
						isPosting: true,
						parentId: "p2",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: "a3",
						code: "1.01.01.03",
						name: "Jago - Budget",
						type: "ASSET",
						isPosting: true,
						parentId: "p2",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: "p3",
				code: "1.01.02.00",
				name: "Kas",
				type: "ASSET",
				isPosting: false,
				parentId: "p1",
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: "a4",
						code: "1.01.02.01",
						name: "Wallet Cash",
						type: "ASSET",
						isPosting: true,
						parentId: "p3",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: "p4",
				code: "1.01.03.00",
				name: "E-Wallet",
				type: "ASSET",
				isPosting: false,
				parentId: "p1",
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: "a5",
						code: "1.01.03.01",
						name: "Gopay",
						type: "ASSET",
						isPosting: true,
						parentId: "p4",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: "a6",
						code: "1.01.03.02",
						name: "Dana",
						type: "ASSET",
						isPosting: true,
						parentId: "p4",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
		],
	},
	{
		id: "p5",
		code: "1.02.00.00",
		name: "Aset Non-Lancar",
		type: "ASSET",
		isPosting: false,
		parentId: null,
		createdAt: "",
		updatedAt: "",
		children: [
			{
				id: "p6",
				code: "1.02.01.00",
				name: "Brokerage Accounts",
				type: "ASSET",
				isPosting: false,
				parentId: "p5",
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: "a7",
						code: "1.02.01.01",
						name: "Stockbit Sekuritas",
						type: "ASSET",
						isPosting: true,
						parentId: "p6",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: "a8",
						code: "1.02.01.02",
						name: "Pluang Sekuritas",
						type: "ASSET",
						isPosting: true,
						parentId: "p6",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: "p7",
				code: "1.02.05.00",
				name: "Saving & Commodities",
				type: "ASSET",
				isPosting: false,
				parentId: "p5",
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: "a9",
						code: "1.02.05.01",
						name: "Gold",
						type: "ASSET",
						isPosting: true,
						parentId: "p7",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: "a10",
						code: "1.02.05.03",
						name: "Emergency Fund",
						type: "ASSET",
						isPosting: true,
						parentId: "p7",
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
		],
	},
];

// ── Dummy balance per account (DR - CR) ───────────────────────────────────
export const dummyBalances: Record<string, number> = {
	a1: 49100000, // Mandiri
	a2: 50000000, // BCA
	a3: 3000000, // Jago
	a4: 2500000, // Wallet Cash
	a5: 800000, // Gopay
	a6: 350000, // Dana
	a7: 12000000, // Stockbit
	a8: 5000000, // Pluang
	a9: 8500000, // Gold
	a10: 15000000, // Emergency Fund
};

// ── Dummy Laporan data ────────────────────────────────────────────────────
export const dummyTrialBalance = [
	{
		code: "1.01.01.02",
		name: "BCA - Main",
		type: "ASSET",
		debit: 52000000,
		credit: 2000000,
	},
	{
		code: "1.01.02.01",
		name: "Kas",
		type: "ASSET",
		debit: 3500000,
		credit: 6000000,
	},
	{
		code: "1.02.05.03",
		name: "Emergency Fund",
		type: "ASSET",
		debit: 15000000,
		credit: 0,
	},
	{
		code: "2.01.01.00",
		name: "Hutang Dagang",
		type: "LIABILITY",
		debit: 1200000,
		credit: 2400000,
	},
	{
		code: "3.00.00.00",
		name: "Modal",
		type: "EQUITY",
		debit: 0,
		credit: 50000000,
	},
	{
		code: "4.01.01.01",
		name: "Pendapatan Jasa",
		type: "REVENUE",
		debit: 0,
		credit: 6000000,
	},
	{
		code: "5.01.01.04",
		name: "Biaya Perlengkapan",
		type: "EXPENSE",
		debit: 500000,
		credit: 0,
	},
	{
		code: "5.04.01.01",
		name: "Beban Gaji",
		type: "EXPENSE",
		debit: 4000000,
		credit: 0,
	},
	{
		code: "5.04.01.02",
		name: "Beban Bonus",
		type: "EXPENSE",
		debit: 1000000,
		credit: 0,
	},
];

export const dummyIncomeStatement = {
	revenues: [{ name: "Pendapatan Jasa", amount: 6000000 }],
	expenses: [
		{ name: "Biaya Perlengkapan", amount: 500000 },
		{ name: "Beban Gaji", amount: 4000000 },
		{ name: "Beban Bonus", amount: 1000000 },
	],
	totalRevenue: 6000000,
	totalExpense: 5500000,
	netIncome: 500000,
};

export const dummyBalanceSheet = {
	currentAssets: [
		{ name: "BCA - Main", balance: 50000000 },
		{ name: "Kas", balance: 2500000 },
		{ name: "Jago - Budget", balance: 3000000 },
	],
	nonCurrentAssets: [
		{ name: "Stockbit Sekuritas", balance: 12000000 },
		{ name: "Emergency Fund", balance: 15000000 },
		{ name: "Gold", balance: 8500000 },
	],
	liabilities: [{ name: "Hutang Dagang", balance: 1200000 }],
	equity: [
		{ name: "Modal", balance: 50000000 },
		{ name: "Laba Periode Ini", balance: 500000 },
	],
	totalCurrentAssets: 55500000,
	totalNonCurrentAssets: 35500000,
	totalAssets: 91000000,
	totalLiabilities: 1200000,
	totalEquity: 50500000,
};

export const dummyCashFlow = {
	operating: {
		lines: [
			{ label: "Penerimaan dari pelanggan", amount: 6000000 },
			{ label: "Pembayaran beban operasi", amount: -5500000 },
			{ label: "Pembayaran hutang dagang", amount: -1200000 },
		],
		total: -700000,
	},
	investing: {
		lines: [{ label: "Pembelian instrumen investasi", amount: -5000000 }],
		total: -5000000,
	},
	financing: {
		lines: [{ label: "Setoran modal", amount: 50000000 }],
		total: 50000000,
	},
	netCashFlow: 44300000,
};
